#!/usr/bin/env python3
import os
import glob
import re

HEADER = """// Do not edit this file; automatically generated by simple_build.py.
'use strict';

"""

def build_blocks():
    files = glob.glob('blocks/*.js')
    with open('blocks_compressed.js', 'w') as out:
        out.write(HEADER)
        for f in sorted(files):
            with open(f) as inp:
                content = inp.read()
                content = re.sub(r"goog\.provide\('Blockly\.Blocks\.(\w+)'\);", r"Blockly.Blocks.\1={};", content)
                content = re.sub(r"goog\.require\([^)]+\);", "", content)
                out.write(content + "\n")
    print("Created blocks_compressed.js")

def build_arduino():
    files = ['generators/arduino.js'] + sorted(glob.glob('generators/arduino/*.js'))
    with open('arduino_compressed.js', 'w') as out:
        out.write(HEADER)
        for f in files:
            with open(f) as inp:
                content = inp.read()
                content = re.sub(r"goog\.provide\('Blockly\.Arduino'\);", "Blockly.Arduino={};", content)
                content = re.sub(r"goog\.require\([^)]+\);", "", content)
                out.write(content + "\n")
    print("Created arduino_compressed.js")

if __name__ == '__main__':
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    build_blocks()
    build_arduino()
