; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc1]
platform = espressif32
board = esp32-s3-devkitc1
framework = arduino
monitor_speed = 115200
lib_deps = 
    arduino-libraries/Servo@^1.1.8
