var BOARD_TEMPLATES = {
  'esp32-s3-devkitc1': {
    'platformio.ini': '[env:esp32-s3-devkitc-1]\nplatform = espressif32\nboard = esp32-s3-devkitc-1\nframework = arduino\n\n; Upload settings\nupload_speed = 921600\nmonitor_speed = 115200\n\n; Build flags for ESP32-S3\nbuild_flags = \n    -DCORE_DEBUG_LEVEL=0\n    -DBOARD_HAS_PSRAM\n    -mfix-esp32-psram-cache-issue\n\n; Libraries\nlib_deps = \n    adafruit/Adafruit NeoPixel@^1.12.0\n    madhephaestus/ESP32Servo@^1.1.1\n\n; Monitor options \nmonitor_filters = esp32_exception_decoder\n',
    'include/servos.h': '#ifndef SERVOS_H\n#define SERVOS_H\n\n#include <Arduino.h>\n\n// Servo pin definitions\n#define SERVO1_PIN 37\n#define SERVO2_PIN 38\n#define SERVO3_PIN 45\n\n// Servo number constants\n#define SERVO1 1\n#define SERVO2 2\n#define SERVO3 3\n\n// Number of servos\n#define NUM_SERVOS 3\n\n// Function to initialize servos\nvoid initializeServos();\n\n// Function to set servo angle\nvoid setServoAngle(int servoNum, int angle);\n\n// Function to read servo angle\nint readServoAngle(int servoNum);\n\n// Function to test single servo sweep\nvoid testServoSweep(int servoNum);\n\n#endif // SERVOS_H\n',
    'src/servos.cpp': '#include "servos.h"\n#include <ESP32Servo.h>\n\n// Servo objects\nServo servo1;\nServo servo2;\nServo servo3;\n\nvoid initializeServos() {\n  servo1.attach(SERVO1_PIN);\n  servo2.attach(SERVO2_PIN);\n  servo3.attach(SERVO3_PIN);\n}\n\nvoid setServoAngle(int servoNum, int angle) {\n  if (angle < 0) angle = 0;\n  if (angle > 180) angle = 180;\n\n  switch (servoNum) {\n    case 1:\n      servo1.write(angle);\n      break;\n    case 2:\n      servo2.write(angle);\n      break;\n    case 3:\n      servo3.write(angle);\n      break;\n    default:\n      Serial.println("Invalid servo number");\n      break;\n  }\n}\n\nint readServoAngle(int servoNum) {\n  switch (servoNum) {\n    case 1:\n      return servo1.read();\n    case 2:\n      return servo2.read();\n    case 3:\n      return servo3.read();\n    default:\n      return -1;\n  }\n}\n\nvoid testServoSweep(int servoNum) {\n  for (int angle = 0; angle <= 180; angle++) {\n    setServoAngle(servoNum, angle);\n    delay(10);\n  }\n  for (int angle = 180; angle >= 0; angle--) {\n    setServoAngle(servoNum, angle);\n    delay(10);\n  }\n}\n',
    'include/internalLED.h': '#ifndef INTERNAL_LED_H\n#define INTERNAL_LED_H\n\n#include <Arduino.h>\n#include <Adafruit_NeoPixel.h>\n\n// Pin definition for WS2812B RGB LED on ESP32-S3 DevKit\n#define RGB_LED_PIN 48\n#define NUM_PIXELS 1\n\n// LED functions\nvoid initializeLED();\nvoid setLED(uint8_t red, uint8_t green, uint8_t blue);\nvoid turnOffLED();\nvoid runLEDInitTest();\n\n#endif // INTERNAL_LED_H\n',
    'src/internalLED.cpp': '#include "internalLED.h"\n\n// Create NeoPixel object\nAdafruit_NeoPixel pixel(NUM_PIXELS, RGB_LED_PIN, NEO_GRB + NEO_KHZ800);\n\nvoid initializeLED() {\n  pixel.begin();\n  pixel.setBrightness(100);\n  turnOffLED();\n}\n\nvoid setLED(uint8_t red, uint8_t green, uint8_t blue) {\n  pixel.setPixelColor(0, pixel.Color(red, green, blue));\n  pixel.show();\n}\n\nvoid turnOffLED() {\n  pixel.setPixelColor(0, pixel.Color(0, 0, 0));\n  pixel.show();\n}\n\nvoid runLEDInitTest() {\n  setLED(255, 0, 0);\n  delay(500);\n  setLED(0, 255, 0);\n  delay(500);\n  setLED(0, 0, 255);\n  delay(500);\n  turnOffLED();\n}\n',
    'include/buttons.h': '#ifndef BUTTONS_H\n#define BUTTONS_H\n\n#include <Arduino.h>\n\n// Button pin definitions\n#define BUTTON1_PIN 4\n#define BUTTON2_PIN 5\n#define BUTTON3_PIN 6\n#define BUTTON4_PIN 7\n\n// Button number constants\n#define BUTTON1 1\n#define BUTTON2 2\n#define BUTTON3 3\n#define BUTTON4 4\n\n// Number of buttons\n#define NUM_BUTTONS 4\n\n// Function to initialize buttons\nvoid initializeButtons();\n\n// Function to read button state (returns true if pressed)\nbool readButton(int buttonNum);\n\n#endif // BUTTONS_H\n',
    'src/buttons.cpp': '#include "buttons.h"\n\nvoid initializeButtons() {\n  pinMode(BUTTON1_PIN, INPUT_PULLUP);\n  pinMode(BUTTON2_PIN, INPUT_PULLUP);\n  pinMode(BUTTON3_PIN, INPUT_PULLUP);\n  pinMode(BUTTON4_PIN, INPUT_PULLUP);\n}\n\nbool readButton(int buttonNum) {\n  int pinState = HIGH;\n  \n  switch (buttonNum) {\n    case 1:\n      pinState = digitalRead(BUTTON1_PIN);\n      break;\n    case 2:\n      pinState = digitalRead(BUTTON2_PIN);\n      break;\n    case 3:\n      pinState = digitalRead(BUTTON3_PIN);\n      break;\n    case 4:\n      pinState = digitalRead(BUTTON4_PIN);\n      break;\n    default:\n      return false;\n  }\n  \n  // Buttons are active LOW (pressed = LOW)\n  return (pinState == LOW);\n}\n',
    'include/LEDMatrix.h': '#ifndef LED_MATRIX_H\n#define LED_MATRIX_H\n\n#include <Arduino.h>\n#include <Adafruit_NeoPixel.h>\n\n// Pin definition for WS2812B RGB LED Matrix on ESP32-S3\n#define LED_MATRIX_PIN 10\n#define NUM_LEDS 16\n\n// LED Matrix functions\nvoid initializeLEDMatrix();\nvoid setLEDMatrixPixel(uint8_t index, uint8_t red, uint8_t green, uint8_t blue);\nvoid fillLEDMatrix(uint8_t red, uint8_t green, uint8_t blue);\nvoid turnOffLEDMatrix();\nvoid showLEDMatrix();\n\n#endif // LED_MATRIX_H\n',
    'src/LEDMatrix.cpp': '#include "LEDMatrix.h"\n\n// Create NeoPixel object for LED Matrix\nAdafruit_NeoPixel ledMatrix(NUM_LEDS, LED_MATRIX_PIN, NEO_GRB + NEO_KHZ800);\n\nvoid initializeLEDMatrix() {\n  ledMatrix.begin();\n  ledMatrix.setBrightness(100);\n  turnOffLEDMatrix();\n}\n\nvoid setLEDMatrixPixel(uint8_t index, uint8_t red, uint8_t green, uint8_t blue) {\n  if (index < NUM_LEDS) {\n    ledMatrix.setPixelColor(index, ledMatrix.Color(red, green, blue));\n  }\n}\n\nvoid fillLEDMatrix(uint8_t red, uint8_t green, uint8_t blue) {\n  for (uint8_t i = 0; i < NUM_LEDS; i++) {\n    ledMatrix.setPixelColor(i, ledMatrix.Color(red, green, blue));\n  }\n}\n\nvoid turnOffLEDMatrix() {\n  for (uint8_t i = 0; i < NUM_LEDS; i++) {\n    ledMatrix.setPixelColor(i, ledMatrix.Color(0, 0, 0));\n  }\n  ledMatrix.show();\n}\n\nvoid showLEDMatrix() {\n  ledMatrix.show();\n}\n',
    '.vscode/settings.json': '{\n  "editor.tabSize": 2,\n  "files.associations": {\n    "*.ino": "cpp"\n  }\n}\n',
    '.gitignore': '.pio\n.vscode/.browse.c_cpp.db*\n.vscode/c_cpp_properties.json\n.vscode/launch.json\n.vscode/ipch\n'
  },
  'arduino-uno': {
    'platformio.ini': '; PlatformIO Project Configuration File\n; https://docs.platformio.org/page/projectconf.html\n\n[env:uno]\nplatform = atmelavr\nboard = uno\nframework = arduino\nmonitor_speed = 9600\nlib_deps = \n    arduino-libraries/Servo@^1.1.8\n',
    '.vscode/settings.json': '{\n  "editor.tabSize": 2,\n  "files.associations": {\n    "*.ino": "cpp"\n  }\n}\n',
    '.gitignore': '.pio\n.vscode/.browse.c_cpp.db*\n.vscode/c_cpp_properties.json\n.vscode/launch.json\n.vscode/ipch\n'
  }
};
